test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, altered_words))
  File "/home/runner/work/c03_ch2_ecriture-tlusignan/c03_ch2_ecriture-tlusignan/exercice.py", line 5, in majuscule
    lettre
UnboundLocalError: local variable 'lettre' referenced before assignment

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
